apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.fullname" . }}-backend
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ include "launchpad.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "launchpad.fullname" . }}-backend
        {{- include "launchpad.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
            - name: DB_MASTER_HOST
              value: {{ include "launchpad.fullname" . }}-mysql
            - name: DB_READER_HOST
              value: {{ include "launchpad.fullname" . }}-mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: database
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-backend-secret
                  key: jwtSecret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-backend-secret
                  key: googleClientId
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}

