apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.fullname" . }}-frontend
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "launchpad.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "launchpad.fullname" . }}-frontend
        {{- include "launchpad.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}

