apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.fullname" . }}-mysql
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "launchpad.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "launchpad.fullname" . }}-mysql
        {{- include "launchpad.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.mysql.repository }}:{{ .Values.image.mysql.tag }}"
          imagePullPolicy: {{ .Values.image.mysql.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.fullname" . }}-mysql-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: mysql-data
          {{- if .Values.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "launchpad.fullname" . }}-mysql-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}

